--------------------ADMININFO----------------------
DROP TABLE ADMININFO CASCADE CONSTRAINTS PURGE;
CREATE TABLE ADMININFO(
  ID NUMBER(11) CONSTRAINT ADMININFO_ID_PK PRIMARY KEY,
  ADMINCODE VARCHAR2(30) CONSTRAINT ADMININFO_ADMINCODE_UK UNIQUE　NOT NULL,
  PASSWORD VARCHAR2(30) NOT NULL,
  NAME VARCHAR2(30) NOT NULL,
  TELEPHONE VARCHAR2(30),
  EMAIL VARCHAR2(50),
  ENROLLDATE DATE NOT NULL
);
DROP SEQUENCE ADMININFO_ID_SQ;
CREATE SEQUENCE ADMININFO_ID_SQ
START WITH 1000
INCREMENT BY 1
NOCACHE
NOMAXVALUE;
--------------------ADMININFO----------------------

--------------------COST----------------------
DROP TABLE COST CASCADE CONSTRAINTS PURGE;
CREATE TABLE COST(
	ID NUMBER(4) CONSTRAINT COST_ID_PK PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL CONSTRAINT COST_NAME_UK UNIQUE,
	BASEDURATION NUMBER(11) DEFAULT 0,
	BASECOST NUMBER(7,2) DEFAULT 0,
	UNITCOST NUMBER(7,4) DEFAULT 0,
	STATUS CHAR(1) CONSTRAINT COST_STATUS_CK CHECK (STATUS IN (0,1,2)),
	DESCR VARCHAR2(100),
	CREATETIME DATE DEFAULT SYSDATE ,
	STARTTIME DATE,
	COSTTYPE CHAR(1) CONSTRAINT COST_COSTTYPE_CK CHECK (COSTTYPE IN (1,2,3))
);
DROP SEQUENCE COST_ID_SQ;
CREATE SEQUENCE COST_ID_SQ
START WITH 100
INCREMENT BY 1
NOCACHE
NOMAXVALUE;
--------------------COST----------------------

--------------------ACCOUNT----------------------
DROP TABLE ACCOUNT CASCADE CONSTRAINTS  PURGE;
CREATE TABLE ACCOUNT(
	 ID NUMBER(9) CONSTRAINT ACCOUNT_ID_PK PRIMARY KEY,
	 RECOMMENDERID	NUMBER(9) CONSTRAINT ACCOUNT_RECOMMENDERID_FK REFERENCES ACCOUNT(ID),      
	 LOGINNAME VARCHAR2(30) NOT NULL CONSTRAINT ACCOUNT_LOGINNAME_UK UNIQUE,      
	 LOGINPASSWORD VARCHAR2(8) NOT NULL, 
	 STATUS CHAR(1)	CONSTRAINT ACCOUNT_STATUS_CK CHECK (STATUS IN (0,1,2)),        
	 CREATEDATE DATE DEFAULT SYSDATE, 
	 PAUSEDATE DATE, 
	 CLOSEDATE DATE, 
	 REALNAME VARCHAR2(20)	NOT NULL, 
	 IDCARDNO CHAR(18) NOT NULL CONSTRAINT ACCOUNT_INCARDNO_UK UNIQUE,      
	 BIRTHDATE DATE, 
	 GENDER CHAR(1) CONSTRAINT ACCOUNT_GENDER_CK CHECK (GENDER IN (0,1)),        
	 OCCUPATION VARCHAR2(50), 
	 TELEPHONE VARCHAR2(15) NOT NULL, 
	 EMAIL VARCHAR2(50), 
	 MAILADDRESS VARCHAR2(50), 
	 ZIPCODE CHAR(6), 
	 QQ VARCHAR2(15), 
	 LASTLOGINTIME DATE, 
	 LASTLOGINIP VARCHAR2(15) 
);
DROP SEQUENCE ACCOUNT_ID_SQ;
CREATE SEQUENCE ACCOUNT_ID_SQ
START WITH 1100
INCREMENT BY 1
NOCACHE
NOMAXVALUE;
--------------------ACCOUNT----------------------

--------------------HOST----------------------
DROP TABLE HOST CASCADE CONSTRAINT PURGE;
CREATE TABLE HOST(
  ID VARCHAR2(15) CONSTRAINT HOST_ID_PK PRIMARY KEY,
  NAME VARCHAR2(20), 
  LOCATION VARCHAR2(20)
);
--------------------HOST----------------------

--------------------SERVICE----------------------
DROP TABLE SERVICE CASCADE CONSTRAINTS PURGE;
CREATE TABLE SERVICE(
	ID NUMBER(10) CONSTRAINT SERVICE_ID_PK PRIMARY KEY, 
	ACCOUNT_ID NUMBER(9) CONSTRAINT SERVICE_ACCOUNT_ID_FK REFERENCES ACCOUNT(ID) NOT NULL,    
	HOST_ID VARCHAR2(15) CONSTRAINT SERVICE_HOST_ID_FK REFERENCES HOST(ID) NOT NULL ,    
	OSUSERNAME	VARCHAR2(8)	NOT NULL,
		CONSTRAINT SERVICE_HOSTNAME_UK UNIQUE(HOST_ID,OSUSERNAME),    
	LOGINPASSWORD VARCHAR2(8) NOT NULL, 
	STATUS CHAR(1) CONSTRAINT SERVICE_STATUS_CK CHECK ( STATUS IN (0,1,2) ),	                      
	CREATEDATE DATE DEFAULT SYSDATE, 
	PAUSEDATE DATE, 
	CLOSEDATE DATE, 
	COST_ID NUMBER(4) CONSTRAINT SERVICE_COST_ID_FK REFERENCES COST(ID) NOT NULL                      
);
DROP SEQUENCE SERVICE_ID_SQ;
CREATE SEQUENCE SERVICE_ID_SQ
START WITH 2100
INCREMENT BY 1
NOCACHE
NOMAXVALUE;
--------------------SERVICE----------------------

--------------------SERVICE_UPDATE_BAK----------------------
DROP TABLE SERVICE_UPDATE_BAK  CASCADE CONSTRAINTS PURGE;
CREATE TABLE SERVICE_UPDATE_BAK(
	ID NUMBER(10) CONSTRAINT SERVICE_UPDATE_BAK_ID_PK PRIMARY KEY, 
	SERVICEID NUMBER(10) CONSTRAINT SERVICE_UPDATE_BAK_SID_FK REFERENCES SERVICE(ID) NOT NULL,    
	UNIXHOST VARCHAR2(15) CONSTRAINT SERVICE_UPDATE_BAK_HOST_FK REFERENCES HOST(ID) NOT NULL ,    
	OSUSERNAME	VARCHAR2(8)	NOT NULL, 
	CONSTRAINT SERVICE_UPDATE_BAK_HOSTOS_UK UNIQUE(UNIXHOST,OSUSERNAME),                           
	CREATEDATE	DATE DEFAULT SYSDATE,  
	COSTID NUMBER(4) CONSTRAINT SERVICE_UPDATA_BAK_CID_FK REFERENCES COST(ID) NOT NULL                      
);

DROP SEQUENCE SERVICE_UPDATE_BAK_ID;
CREATE SEQUENCE SERVICE_UPDATE_BAK_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOMAXVALUE;
--------------------SERVICE----------------------

--------------------ROLEINFO----------------------
DROP TABLE ROLEINFO CASCADE CONSTRAINTS PURGE;
CREATE TABLE ROLEINFO(
	ID NUMBER(11) PRIMARY KEY,
	NAME VARCHAR2(20) NOT NULL UNIQUE
);
DROP SEQUENCE ROLEINFO_ID_SQ;
CREATE SEQUENCE ROLEINFO_ID_SQ
START WITH 20
INCREMENT BY 1
NOCACHE
NOMAXVALUE;
--------------------ROLEINFO----------------------


----------------------PRIVILEGE---------------------------
DROP TABLE PRIVILEGE CASCADE CONSTRAINTS PURGE;
CREATE TABLE PRIVILEGE(
  ID NUMBER(4) PRIMARY KEY,
  MODULENAME VARCHAR2(20) NOT NULL UNIQUE,
  URL VARCHAR(400)
);
DROP SEQUENCE PRIVILEGE_ID_SQ;
CREATE SEQUENCE PRIVILEGE_ID_SQ
START WITH 20
INCREMENT BY 1
NOCACHE
NOMAXVALUE;
----------------------PRIVILEGE---------------------------

--------------------ADMIN_ROLE----------------------
DROP TABLE ADMIN_ROLE CASCADE CONSTRAINTS PURGE;
CREATE TABLE ADMIN_ROLE(
	ADMININFO_ID NUMBER(4) NOT NULL CONSTRAINTS ADMIN_ROLE_ADMININFOID_FK REFERENCES ADMININFO(ID),
	ROLEINFO_ID NUMBER(4) NOT NULL CONSTRAINTS ADMIN_ROLE_ROLEINFOID_FK REFERENCES ROLEINFO(ID),
	CONSTRAINT ADMIN_ROLE_CASCADE_UK UNIQUE(ADMININFO_ID,ROLEINFO_ID)
);
--------------------ADMIN_ROLE----------------------

----------------------ROLEINFO_PRIVILEGE---------------------------
DROP TABLE ROLEINFO_PRIVILEGE CASCADE CONSTRAINTS PURGE;
CREATE TABLE ROLEINFO_PRIVILEGE(
	ROLEINFO_ID NUMBER(4) NOT NULL CONSTRAINT ROLE_PRIVILEGE_ROLEID_FK REFERENCES ROLEINFO(ID),
	PRIVILEGE_ID NUMBER(4) NOT NULL CONSTRAINT ROLE_PRIVILEGE_PRIVILEGE_FK REFERENCES PRIVILEGE(ID),
  	CONSTRAINT ROLEINFO_PRIVILEGE_CASCADE_UK UNIQUE(ROLEINFO_ID,PRIVILEGE_ID)
);
----------------------ROLEINFO_PRIVILEGE---------------------------

----------------------SERVICE_DETAIL---------------------------
DROP TABLE SERVICE_DETAIL CASCADE CONSTRAINT PURGE;
CREATE TABLE SERVICE_DETAIL(
	ID NUMBER(11) CONSTRAINT SERVICE_DETAIL_ID_PK PRIMARY KEY,
	SERVICE_ID NUMBER(10) CONSTRAINT SERVICE_DETAIL_SERVICE_ID REFERENCES SERVICE(ID) NOT NULL,
	CLIENTHOST VARCHAR2(15),
	OSUSERNAME VARCHAR2(8),
	PID NUMBER(11),
	LOGINTIME DATE,
	LOGOUTTIME DATE,
	DURATION NUMBER(20,9),
	COST NUMBER(20,6) DEFAULT 0
);
DROP SEQUENCE SERVICE_DETAIL_SEQ;
CREATE SEQUENCE SERVICE_DETAIL_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOMAXVALUE;
----------------------SERVICE_DETAIL---------------------------


---------------------------MONTH_DURATION---------------------------
DROP TABLE MONTH_DURATION CASCADE CONSTRAINTS PURGE;
CREATE TABLE MONTH_DURATION(
	SERVICE_ID NUMBER(10),
	MONTH_ID CHAR(6),
	CONSTRAINT MONTH_DURATION_PK PRIMARY KEY(SERVICE_ID,MONTH_ID),
	SERVICE_DETAIL_ID NUMBER(11),
	SOFAR_DURATION NUMBER(11)
);
---------------------------MONTH_DURATION---------------------------

---------------------------BILL---------------------------
DROP TABLE BILL CASCADE CONSTRAINTS PURGE;
CREATE TABLE BILL(
	ID NUMBER(11) CONSTRAINT BILL_ID_PK PRIMARY KEY,
	ACCOUNT_ID NUMBER(9) CONSTRAINT BILL_ACCOUNT_ID REFERENCES ACCOUNT(ID) NOT NULL,
	BILLMONTH CHAR(6),
	COST NUMBER(13,2),
	PAYMENTMODE CHAR(1) CONSTRAINT BILL_PAYMENTCODE_CK CHECK (PAYMENTMODE IN (0,1,2,3)),
	PAYSTATE CHAR(10) DEFAULT 0 CONSTRAINT BILL_PAYSTATE_CK CHECK (PAYSTATE IN (0,1)) 
);
DROP SEQUENCE SEQ_BILL_ID;
CREATE SEQUENCE SEQ_BILL_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOMAXVALUE;
---------------------------BILL---------------------------

---------------------------BILLITEM---------------------------
DROP TABLE BILLITEM CASCADE CONSTRAINTS PURGE;
CREATE TABLE BILLITEM(
	ID NUMBER(11) CONSTRAINT BILLITEM_ID_PK  PRIMARY KEY,
	BILL_ID NUMBER(11) CONSTRAINT BILLITME_BILL_ID_FK REFERENCES BILL(ID) NOT NULL,
	SERVICE_ID NUMBER(10) CONSTRAINT BILLITME_SERVICE_ID_FK REFERENCES SERVICE(ID) NOT NULL,
	COST NUMBER(13,2)
);
DROP SEQUENCE SEQ_BILLITEM_ID;
CREATE SEQUENCE SEQ_BILLITEM_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOMAXVALUE;
---------------------------BILLITEM---------------------------

---------------------------BILL_CODE---------------------------
DROP TABLE BILL_CODE CASCADE CONSTRAINT PURGE;
CREATE GLOBAL TEMPORARY TABLE BILL_CODE(
	BILL_ID NUMBER(11),
	ACCOUNT_ID NUMBER(9),
	BILL_MONTH CHAR(6)
) ON COMMIT PRESERVE ROWS;
---------------------------BILL_CODE---------------------------

---------------------------BILL_ITEM_TEMP---------------------------
DROP TABLE BILL_ITEM_TEMP;
CREATE GLOBAL TEMPORARY TABLE BILL_ITEM_TEMP(
  ITEM_ID NUMBER(11),
  BILL_ID NUMBER(11),
  SERVICE_ID NUMBER(10) NOT NULL,
  COST NUMBER(13,2)
) ON COMMIT PRESERVE ROWS;
---------------------------BILL_ITEM_TEMP---------------------------